name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Nuget restore
        run: Nuget restore

      - name: Build app for release
        run:  msbuild .\EF6.sln -t:rebuild -verbosity:diag -property:Configuration=Release
        
      - name: Install localdb
        uses: potatoqualitee/mssqlsuite@v1
        with:
          install: localdb

      - name: Run Unit Tests
        run: dotnet test .\Tests\Globalmantics.UnitTests\Globalmantics.UnitTests.csproj --logger "trx;LogFileName=test-result.trx"

      - name: Run Integration Tests
        run: dotnet test .\Tests\Globalmantics.IntegrationTests\Globalmantics.IntegrationTests.csproj --logger "trx;LogFileName=test-result.trx"
      
      - name: Unit Test Report
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: '.\Tests\Globalmantics.UnitTests\TestResults\*.trx'

      - name: Integration Test Report
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: integration-test-results
          path: '.\Tests\Globalmantics.IntegrationTests\TestResults\*.trx'    

  report:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            
        name: Unit Tests                  
        path: 'test-result.trx'          
        reporter: dotnet-trx      

    - uses: dorny/test-reporter@v1
      with:
        artifact: integration-test-results            
        name: Integration Tests                 
        path: 'test-result.trx'          
        reporter: dotnet-trx