name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: Unit Tests                  # Name of the check run which will be created
        path: 'test-result.trx'           # Path to test results (inside artifact .zip)
        reporter: dotnet-trx      

    - uses: dorny/test-reporter@v1
      with:
        artifact: integration-test-results            # artifact name
        name: Integration Tests                  # Name of the check run which will be created
        path: 'test-results.trx'           # Path to test results (inside artifact .zip)
        reporter: dotnet-trx             